name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-website:${{ github.sha }} .
      
      # Step 4: Push the image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-website:${{ github.sha }}
          
      # Step 5: Optionally, push the 'latest' tag
      - name: Push 'latest' tag
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-website:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-website:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-website:latest
